### PR TITLE
Black box tests

### PR DESCRIPTION
**Pull request by Eirik0**
This adds a method for generating a random element of Fq and using that adds black-box tests for associativity, identity, inverse, and commutativity.

### CODE REVIEW

**Comment by ebfull** [comment]
Let's do this instead:

1. make `rand` a `dev-dependency` rather than a normal dependency so that downstream users don't need it and all its transitive dependencies if they're doing their own key derivations or whatever.
2. expose `from_bytes_wide` as we are; don't expose `from_u512` though.

**Comment by ebfull** [comment]
We should leave a comment...

```
// We reduce an arbitrary 512-bit number by decomposing it into two 256-bit digits
// with the higher bits multiplied by 2^256. Thus, we perform two reductions
//
// 1. the lower bits are multiplied by R^2, as normal
// 2. the upper bits are multiplied by R^2 * 2^256 = R^3
// 
// and computing their sum in the field. It remains to see that arbitrary 256-bit
// numbers can be placed into Montgomery form safely using the reduction. The
// reduction works so long as the product is less than R=2^256 multipled by
// the modulus. This holds because for any `c` smaller than the modulus, we have
// that (2^256 - 1)*c is an acceptable product for the reduction. Therefore, the
// reduction always works so long as `c` is in the field; in this case it is either the
// constant `R2` or `R3`.
```

**Comment by Eirik0** [comment]
I've implemented `Distribution<Fq> for Standard`, used `XorShiftRng`, and made `rand` a `dev-dependency`.  I also upped the number of checks to 2000 from 20 and added the above comment (in favor of one I had which looking again, I wasn't too sure was correct). I had to move the black-box tests to `fq.rs` because I couldn't get the `dev-dependency` working correctly when they were in a separate file. I also made `from_u512` private, but I didn't merge it with the other function because I think it is more convenient for testing - that being said I am happy to change this if we prefer them merged.

**Comment by Eirik0** [comment]
Splitting this in to two separate PRs. One which implements from_bytes_wide (#15), and a second one for generating the random elements of Fq and Fr for black-box testing.

**Comment by Eirik0** [comment]
This has been accomplished in other PRs. Closing.

**Pull request closed without merging**
