### PR TITLE
Fq inverse (addition chain for fq)

### PR DESCRIPTION
**Pull request by Eirik0**
This PR is to add an addition chain for performing faster inversion over Fq. According to the benchmark it takes about half the time that the naive way does.

This is using the baseline addition presented by @ValarDragon in https://github.com/zkcrypto/jubjub/issues/1

I wrote a simple program in Java to convert the output in to rust code. I can share that tool if it useful or when we do teh same for Fr.

### CODE REVIEW

**Comment by ebfull** [comment]
Two things:

1. Can your java program roll together sequences of squarings (i suppose, more than one) into a loop like `for _ in 0..8`? LLVM will then have more flexibility to inline or unroll the loop depending on what it thinks is best. It may make the code smaller also, but that's not very important to me.
2. Let's modify the test for `pow_q_minus_2` to exercise `pow` using the exponent we had before, since I think it doesn't have a test exercising it after we make this change.

**Comment by Eirik0** [comment]
I can do that. I had considered adding the following function:
```
    #[inline(always)]
    fn square_assign_multi(n: &mut Fq, num_times: usize) {
        for _ in 0..num_times {
            n.square_assign();
        }
    }
```
but not knowing exactly what the compiler would do I wondered if it was better to just inline it manually.

What do you think?

**Comment by Eirik0** [comment]
Regarding square_assign_multi, I am not sure if this made more sense as a member function. I think I actually prefer it that that way but wanted to double check. It might be more ergonomic to say `n.square_assign_multi(i)` than `Fq::square_assign_multi(&mut n, i)`

Also, if we had square and mul functions (rather than square_assign, and mul_assign) we could save about 20 more lines of code. If/when this is done I can regenerate pow_q_minus_2 with this in mind.

**Comment by ebfull** [comment]
Great!

**Pull request merged**
